### ISSUE TITLE
Negative range

### ISSUE THREAD

**Issue by mdosch** [simon-r/dr14_t.meter#13]
dr14_t.meter gave me negative ranges for a short song (Napalm Death - You Suffer).

cat ~/Musik/Napalm\ Death/2012\ -\ Scum\ (Full\ Dynamic\ Range\ 2012\ Edition)/dr14.txt | grep Suffer
 DR-47   -1.31 dB    -26.59 dB  0:06    12 - You Suffer      [mp3]  
 DR-19   -2.16 dB    -25.61 dB  0:06    40 - You Suffer (Rough Mix)      [mp3]

**Comment by Sami-Perkele** [comment]
One very short track returned -48 with dr14_t.meter but +22 with the Foobar plugin.
Track in question is (Näin on) by Eppu Normaali from album Aknepop (original master).

**Comment by simon-r** [comment]
What's the result with the official meter?

[Do you have a working link for listening this track?]

**Comment by Sami-Perkele** [comment]
I uploaded it https://metacrane.com/c/eppunormaali
It’s available for the next 56 hours. I don’t think uploading a track that short can be considered copyright infringement. :D It’s just those two words spoken.

**Comment by Sami-Perkele** [comment]
Well, the official meter gives -48 as well. (I had to decode the flac first because it does not support flac files).

**Comment by simon-r** [comment]
Thanks, I've seen the track.
Is a borderline track, whit only a very short pert of "music" and the rest is silenced.

The description of the algorithm don't say anything about this kind of tracks, and generally is designed for handle more common music track.  

I'm happy that the official meter return a result equivalent to the mine.

Thanks for you report.
