### ISSUE TITLE
Can't handle non-ascii characters in directory name with --quiet option

### ISSUE THREAD

**Issue by welpo** [simon-r/dr14_t.meter#22]
If the directory where dr14 has to run has a character like ü or é it simply won't work when the --quiet argument is used.
Here's the output, the directory name was 'tést':
Traceback (most recent call last):
  File "/media/b0e3/home/welpo/bin/dr14_tmeter", line 26, in <module>
    dr14tmeter.dr14_tmeter.main()
  File "/media/b0e3/home/welpo/.local/lib/python2.7/site-packages/dr14tmeter/dr14_tmeter.py", line 74, in main
    print_msg( path_name )
  File "/media/b0e3/home/welpo/.local/lib/python2.7/site-packages/dr14tmeter/out_messages.py", line 54, in print_msg
    message_file.write( "%s\n" % string )
  File "/usr/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

If I run it without the --quiet option it will work just fine.

**Comment by simon-r** [comment]
Plz. use python 3.
I know the problem, but due to the difference between py3 and py2 is a bit difficult to handle.

**Comment by brendan-pike** [comment]
I think this issue continues to show block; I'm using the latest Mint package 1.0.16-1.

> Traceback (most recent call last):
>   File "/usr/bin/dr14_tmeter", line 26, in <module>
>     dr14tmeter.dr14_tmeter.main()
>   File "/usr/lib/pymodules/python2.7/dr14tmeter/dr14_tmeter.py", line 118, in main
>     (success,clock,r) = scan_dir_list(subdirlist,options,out_dir)
>   File "/usr/lib/pymodules/python2.7/dr14tmeter/dr14_utils.py", line 98, in scan_dir_list
>     write_results( dr , options , out_dir , cur_dir )        
>   File "/usr/lib/pymodules/python2.7/dr14tmeter/dr14_utils.py", line 173, in write_results
>     dr.fwrite_dr( os.path.join( full_out_dir , tables_list[code][0] ) , tables_list[code][1] , table_format , append=options.append , dr_database=options.dr_database )
>   File "/usr/lib/pymodules/python2.7/dr14tmeter/dynamic_range_meter.py", line 141, in fwrite_dr
>     out_file.write( self.table_txt )
>   File "/usr/lib/python2.7/codecs.py", line 706, in write
>     return self.writer.write(data)
>   File "/usr/lib/python2.7/codecs.py", line 369, in write
>     data, consumed = self.encode(object, self.errors)
>   File "/usr/lib/python2.7/encodings/utf_8_sig.py", line 82, in encode
>     return encode(input, errors)
>   File "/usr/lib/python2.7/encodings/utf_8_sig.py", line 15, in encode
>     return (codecs.BOM_UTF8 + codecs.utf_8_encode(input, errors)[0], len(input))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 689: ordinal not in range(128)

**Comment by kmikita** [comment]
Fix for python2:

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

```
--- ./out_messages.py.orig	2023-10-18 11:11:49.760268886 +0300
+++ ./out_messages.py		2023-10-18 11:05:47.430564537 +0300
@@ -19,6 +19,9 @@
 import logging
 import codecs
 
+reload(sys)
+sys.setdefaultencoding('utf-8')
+
 message_file = sys.stderr
 out_file = sys.stdout
 err_file = sys.stderr
```
