### ISSUE TITLE
Host DR14 T.meter packages on Github

### ISSUE THREAD

**Issue by 07416** [simon-r/dr14_t.meter#25]
I tried installing DR14 T.meter from Sourceforge, but the domain `tiny.cc` is blocked in [Malware  Domains](http://www.malwaredomains.com) hosts file and I don't want to visit that site. Can you move the packages to a more safe location? 
I'm not sure if Sourceforge has made some changes recently or the domain has been just added to MD hosts file. Also, Fedora rpm package worked without any issues on openSUSE so you might want to add openSUSE as a supported platform.

**Comment by simon-r** [comment]
tiny.cc is an URL shortening.
I've never noticed any problem whit this service.

Ok for Suse.

**Comment by reddit-is-fun** [comment]
Well, at least uBlock Origin blocks sourceforge.com by default and many users don't want to go to that website. I'd rather install from here or I have to compile from source.

**Comment by simon-r** [comment]
sourceforge.com is filled with announcements, but it don't seems a pishing/malaware site.
Strange.

**Comment by reddit-is-fun** [comment]
Here are some sources: http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/
http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/
http://www.information-age.com/industry/software/123459675/hotbed-malware-another-blow-sourceforge-google-discovers-588-pages-malicious-software
https://www.reddit.com/r/linux/comments/38ebj4/dont_like_whats_happening_with_sourceforge/

If by any means possible, please move everything to Github.

**Comment by simon-r** [comment]
The situation:
Actually the package hosting on github has been removed, via github it's possible to download only the git tag; so it's impossible to offers the distro related packages. Maybe I'm moving on doropbox.

For the home page: Sourceforge offers the possibility to install mediawiki, and it's extremely comfortable for maintaining  a good looking site.

**Comment by SzieberthAdam** [comment]
Hi all!

Note that GitHub releases can also contain binary files:

https://help.github.com/articles/distributing-large-binaries/
https://help.github.com/articles/creating-releases/

**Comment by reddit-is-fun** [comment]
Do you use URL shortening services or was that done by Sourceforge? Please don't if you can decide.

**Comment by simon-r** [comment]
@ SzieberthAdam 
Yes actually I'm using this release system, but it's based only on the git-tag. And it's de facto impossible to put some distro related packages.

@ reddit-is-fun
I'm using this service.

**Comment by magicgoose** [comment]
@07416 it seems it can be installed from pip

```
$ pip3 search dr14
DR14-T.meter (1.0.16)  - Compute the DR14 of a given audio file according to the procedure described by the Pleasurize Music Foundation
```

https://pypi.python.org/pypi
https://en.wikipedia.org/wiki/Pip_(package_manager)

**Comment by 07416** [comment]
The issue appear to have no current relevance.
