### ISSUE TITLE
'Python int too large to convert to C long'

### ISSUE THREAD

**Issue by spvkgn** [simon-r/dr14_t.meter#34]
```
$ soxi Iron\ Maiden\ -\ 205.\ Empire\ Of\ The\ Clouds.flac 

Input File     : 'Iron Maiden - 205. Empire Of The Clouds.flac'
Channels       : 2
Sample Rate    : 48000
Precision      : 24-bit
Duration       : 00:18:01.31 = 51902874 samples ~ 81098.2 CDDA sectors
File Size      : 228M
Bit Rate       : 1.68M
Sample Encoding: 24-bit FLAC
```
dr14_tmeter fails with unexpected error:
```
$ dr14_tmeter -f Iron\ Maiden\ -\ 205.\ Empire\ Of\ The\ Clouds.flac 
/tmp/Iron Maiden - 2015 - The Book Of Souls/Iron Maiden - 205. Empire Of The Clouds.flac

Unexpected error: (<type 'exceptions.OverflowError'>, OverflowError('Python int too large to convert to C long',), <traceback object at 0xb5c48af4>)

 - ERROR ! 
Error: invalid audio file
```
The file is not corrupted:
```
$ flac -wt Iron\ Maiden\ -\ 205.\ Empire\ Of\ The\ Clouds.flac 

flac 1.3.1, Copyright (C) 2000-2009  Josh Coalson, 2011-2014  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

Iron Maiden - 205. Empire Of The Clouds.flac: ok              
```

**Comment by magicgoose** [comment]
What are the results if you scan this with "official" DR scanner?

**Comment by spvkgn** [comment]
I'm on Linux, with foobar2k DR plugin launched through wine gives this results:

![-dynamic range meter 1 1 1](https://cloud.githubusercontent.com/assets/4147135/23586530/33a2e17e-01c1-11e7-9146-1d1a3d20fe67.png)

**Comment by magicgoose** [comment]
So the peak level is not even close to the maximum, that's indeed strange then
What if the file gets converted to another format before scanning with dr14? (WAV, for example)
Are there similar errors with other files in 24 bit FLAC?

**Comment by simon-r** [comment]
It seems a problem with ffmpeg.
Try to read and convert your file with ffmpeg. 

 ffmpeg -i  "imput_file.flac" -b 16 -ar 44100 -y "out_file.wav"

I'm using ffmpeg for reading the flac.

**Comment by magicgoose** [comment]
>-b 16

this will convert to 16 bit and lose precision

**Comment by simon-r** [comment]
Yes!
But this not change the value of the DR14.

The dynamic range is a ratio and has nothing to do with the precision.

**Comment by magicgoose** [comment]
yeah I know. that might change peak levels by a very very small amount.
maybe better idea is first try updating ffmpeg (if it's from a GNU/Linux repository then it might be outdated version)

**Comment by spvkgn** [comment]
Thanks for your tips. So I tried re-download the file and it works well so far.

**Comment by simon-r** [comment]
You must also consider that the audio files sometime are encoded with bug or strange tags.
So also a popular application like ffmpeg sometime fails.

In my collection I've some "unsolved" tracks.
