### ISSUE TITLE
Clarification of the formula used

### ISSUE THREAD

**Issue by sp-1234** [simon-r/dr14_t.meter#36]
I'd start from this quote from description
> DR14 T.meter is a free and open source command line tool for computing the DR - Dynamic Range of your music **according to the procedure used in the off-line meter released by the Pleasurize Music Foundation.**

(emphasis mine)

I tried searching the web and didn't find their definition. (maybe because I'm just too dumb)
May I ask you to add a link to the definition of the procedure?

Or if it was acquired by reverse engineering, then could you write down the formula in simple math terms (i.e. not code), without the simplifications/optimizations mentioned in #35?

I'm asking because I think I might try doing completely identical (to the original tool) computation…

**Comment by Hawke** [comment]
I believe the specification is here: http://www.dynamicrange.de/sites/default/files/Measuring%20DR%20ENv3.pdf

hope this helps.

**Comment by simon-r** [comment]
Yes that's the official description of the used procedure.

**Comment by sp-1234** [comment]
One more question:  
in this project's code, when computing the block size in samples, there's special case for 44100hz:

```
    if Fs == 44100:
        delta_fs = 60
    else:
        delta_fs = 0
…
    block_samples = block_time * ( Fs + delta_fs )
```
That means, for 44100hz blocks are not exactly 3 seconds but slightly more?
Why it's done like this?

**Comment by simon-r** [comment]
Yes.
That's the description of the procedure.
132480 / 3 = 44160 
So I've added this delta.
