### ISSUE TITLE
Is there an important reason for non-standard code formatting?

### ISSUE THREAD

**Issue by magicgoose** [simon-r/dr14_t.meter#37]
The standard format is defined here https://www.python.org/dev/peps/pep-0008

(in particular, https://www.python.org/dev/peps/pep-0008/#pet-peeves which violation bugs me the most…)

There's a good reason why standard formatting style exists, because otherwise everybody would use some arbitrary format and contributors would have to re-adapt eyes each time they switch project. Not to mention potentially more merge conflicts when some people do identical change but with different format (this is possible because a custom yet undefined format is used)

If there are no important reasons for non-standard format, I could make a Pull Request which will normalize formatting in all .py files to PEP-8 **(wherever it's clearly not breaking anything, of course)**. This will make all subsequent contributions easier. ;)

Deal?

**Comment by simon-r** [comment]
How do you have done this style correction?

**Comment by magicgoose** [comment]
@simon-r I didn't do it yet because I decided to ask before (maybe there are reasons why it's the way it is), but PyCharm IDE can do some automatic formatting of Python code, which I intend to use. By default it's set to match PEP-8.
I think there are also some other tools with similar capabilities.

**Comment by simon-r** [comment]
Visual studio code signal a warning but must be corrected by hand.
There is also some command line tools (pylint), but generally do not perform an automatic correction.

**Comment by magicgoose** [comment]
So what do you think about adopting PEP-8?

**Comment by simon-r** [comment]
If you use an editor with an automatic correction I agree.

Please propose a pull request for every single file and not a single request for the entire project!

**Comment by magicgoose** [comment]
That's doable… I'll start with most "interesting" files then.
