### ISSUE TITLE
dr14_tmeter leaves TTY in an inconsistent state somehow

### ISSUE THREAD

**Issue by andlabs** [simon-r/dr14_t.meter#48]
After running dr14_tmeter, I always have to run `stty sane` afteward to get my console window working properly again; otherwise there's no stdin echo or newlines. Piping to `cat` doesn't prevent this behavior. Not sure what's going on; I don't see anything wrecking console modes immediately in the source (unless I'm missing it?).

OS X 10.11

Thanks.

**Comment by simon-r** [comment]
Try now!

**Comment by andlabs** [comment]
Sorry for the lack of response! I just tried it on master, and it does work correctly now. Thanks!

I did have to change the shebang in the main binary from

```
#!/usr/bin/python3
```

to

```
#!/usr/bin/env python3
```

to make it work with the python3 from Homebrew on macOS (as macOS does not come with Python 3 and Homebrew does not install to `/usr/bin`), but that's probably a separate issue.
