### ISSUE TITLE
please update .deb package

### ISSUE THREAD

**Issue by spvkgn** [simon-r/dr14_t.meter#50]
.deb package from SourceForge depends on `python-support` package which [no longer exists in Ubuntu 16.04 repos](https://bugs.launchpad.net/ubuntu/+source/python-support/+bug/1577172). If it's possible please update package for Ubuntu 16.04 and newer.

**Comment by simon-r** [comment]
Could you make a push request with the corrected .deb packager?

**Comment by spvkgn** [comment]
@simon-r I did upload 1.96.0 .deb to https://github.com/spvkgn/dr14_t.meter/releases/tag/v1.96.0
