### ISSUE TITLE
TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by mporembs** [simon-r/dr14_t.meter#60]
I'm trying to use this on FreeBSD 12.1, if that's relevant in any way.

The files are scanned just fine, however I can't successfully write any output. No matter what options (with or without "-b", etc).

My knowledge of Python is admittedly pretty poor. Anyone able to help me out or give me some clues?

> Traceback (most recent call last):
> File "/usr/local/bin/dr14_tmeter", line 26, in <module>
>     dr14tmeter.dr14_tmeter.main()
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/dr14_tmeter.py", line 166, in main
>     (success, clock, r) = scan_dir_list(subdirlist, options, out_dir)
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/dr14_utils.py", line 87, in scan_dir_list
>     write_results(dr, options, out_dir, cur_dir)
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/dr14_utils.py", line 161, in write_results
>     append=options.append, dr_database=options.dr_database)
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/dynamic_range_meter.py", line 146, in fwrite_dr
>     self.table_txt = wr.write_dr(self, tm)
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/write_dr.py", line 183, in write_dr
>     tm.append_separator_line()
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/table.py", line 189, in append_separator_line
>     ["----------------------------------------------------------------------------------------------"])
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/table.py", line 110, in append_row
>     self.end_row()
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/table.py", line 211, in end_row
>     self._append_txt(self.nl())
>   File "/usr/local/lib/python3.6/site-packages/dr14tmeter/table.py", line 63, in _append_txt
>     self.__txt += txt
> TypeError: must be str, not NoneType

**Comment by simon-r** [comment]
Try now

**Comment by mporembs** [comment]
Working now. Thanks for the quick fix.
